-- Confirm Your Account is on the AWS Platform
select current_region();

-- Register Your Snowflake Account Locator With Snowflake
select current_account();

------------------------------------------------------------------------------------------------------------------
-- Rivery Set-up :

GRANT CREATE SCHEMA ON DATABASE IDENTIFIER('PC_RIVERY_DB') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT USAGE ON DATABASE IDENTIFIER('PC_RIVERY_DB') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT ADD SEARCH OPTIMIZATION ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE EXTERNAL TABLE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE FILE FORMAT ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE FUNCTION ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE MASKING POLICY ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE MATERIALIZED VIEW ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE PIPE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE PROCEDURE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE ROW ACCESS POLICY ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE SEQUENCE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE SESSION POLICY ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE STAGE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE STREAM ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE TABLE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE TAG ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE TASK ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE TEMPORARY TABLE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT CREATE VIEW ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT MODIFY ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT MONITOR ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');

GRANT USAGE ON SCHEMA IDENTIFIER('PC_RIVERY_DB.PUBLIC') TO ROLE IDENTIFIER('PC_RIVERY_ROLE');